// Para cada sistema seleccionable (ver lib/systems.ts), la lista ordenada de
// las 11 posiciones que ese sistema reparte en cancha. Es lo que permite que,
// al elegir un sistema para un partido, el XI se arme mostrando exactamente
// esas posiciones a rellenar en vez de dejar que se elija cualquier posición
// para cualquier jugador.
const TEMPLATES: Record<string, string[]> = {
  '4-4-2': [
    'Arquero',
    'Lateral derecho',
    'Central derecho',
    'Central izquierdo',
    'Lateral izquierdo',
    'Extremo derecho',
    'Medio centro derecho',
    'Medio centro izquierdo',
    'Extremo izquierdo',
    'Delantero centro',
    'Segundo delantero',
  ],
  '4-3-3': [
    'Arquero',
    'Lateral derecho',
    'Central derecho',
    'Central izquierdo',
    'Lateral izquierdo',
    'Medio centro derecho',
    'Volante central',
    'Medio centro izquierdo',
    'Extremo derecho',
    'Extremo izquierdo',
    'Delantero centro',
  ],
  '4-2-3-1': [
    'Arquero',
    'Lateral derecho',
    'Central derecho',
    'Central izquierdo',
    'Lateral izquierdo',
    'Medio centro derecho',
    'Medio centro izquierdo',
    'Mediapunta',
    'Extremo derecho',
    'Extremo izquierdo',
    'Delantero centro',
  ],
  '4-1-4-1': [
    'Arquero',
    'Lateral derecho',
    'Central derecho',
    'Central izquierdo',
    'Lateral izquierdo',
    'Volante central',
    'Extremo derecho',
    'Medio centro derecho',
    'Medio centro izquierdo',
    'Extremo izquierdo',
    'Delantero centro',
  ],
  '4-3-1-2': [
    'Arquero',
    'Lateral derecho',
    'Central derecho',
    'Central izquierdo',
    'Lateral izquierdo',
    'Medio centro derecho',
    'Volante central',
    'Medio centro izquierdo',
    'Mediapunta',
    'Delantero centro',
    'Segundo delantero',
  ],
  '4-4-1-1': [
    'Arquero',
    'Lateral derecho',
    'Central derecho',
    'Central izquierdo',
    'Lateral izquierdo',
    'Extremo derecho',
    'Medio centro derecho',
    'Medio centro izquierdo',
    'Extremo izquierdo',
    'Mediapunta',
    'Delantero centro',
  ],
  '4-2-2-2': [
    'Arquero',
    'Lateral derecho',
    'Central derecho',
    'Central izquierdo',
    'Lateral izquierdo',
    'Medio centro derecho',
    'Medio centro izquierdo',
    'Extremo derecho',
    'Extremo izquierdo',
    'Delantero centro',
    'Segundo delantero',
  ],
  '3-4-3': [
    'Arquero',
    'Central derecho',
    'Central',
    'Central izquierdo',
    'Carrilero derecho',
    'Medio centro derecho',
    'Medio centro izquierdo',
    'Carrilero izquierdo',
    'Extremo derecho',
    'Delantero centro',
    'Extremo izquierdo',
  ],
  '3-4-2-1': [
    'Arquero',
    'Central derecho',
    'Central',
    'Central izquierdo',
    'Carrilero derecho',
    'Medio centro derecho',
    'Medio centro izquierdo',
    'Carrilero izquierdo',
    'Mediapunta derecho',
    'Mediapunta izquierdo',
    'Delantero centro',
  ],
  '3-5-2': [
    'Arquero',
    'Central derecho',
    'Central',
    'Central izquierdo',
    'Carrilero derecho',
    'Medio centro derecho',
    'Volante central',
    'Medio centro izquierdo',
    'Carrilero izquierdo',
    'Delantero centro',
    'Segundo delantero',
  ],
  '5-3-2': [
    'Arquero',
    'Carrilero derecho',
    'Central derecho',
    'Central',
    'Central izquierdo',
    'Carrilero izquierdo',
    'Medio centro derecho',
    'Volante central',
    'Medio centro izquierdo',
    'Delantero centro',
    'Segundo delantero',
  ],
  '5-4-1': [
    'Arquero',
    'Carrilero derecho',
    'Central derecho',
    'Central',
    'Central izquierdo',
    'Carrilero izquierdo',
    'Extremo derecho',
    'Medio centro derecho',
    'Medio centro izquierdo',
    'Extremo izquierdo',
    'Delantero centro',
  ],
};

export function formationSlots(sistema: string): string[] | null {
  return TEMPLATES[sistema] || null;
}
